class Rule < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :channel
  has_and_belongs_to_many :applications
  # validations ...............................................................
  validates :ratio, :presence => true, :numericality => true
  validates :activate_at, :presence => true
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  encrypted_id key: 'hLno9CxUoHx6gWrJ'
  # class methods .............................................................
  def self.reformat
    self.all.map { |rule| [rule.ratio, rule.activate_at] }
  end
  # public instance methods ...................................................
  def relate_applications(applications)
    self.applications.delete_all
    self.applications << applications
  end

  def activate_at
    self[:activate_at].try(:to_date)
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
